ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MH1,MDL_MT,MDL_MW,MDL_MZ,MDL_MZ1,MDL_MB
     $ ,MDL_MW1,MDL_MH,MDL_MT1

      COMMON/MASSES/ MDL_MH1,MDL_MT,MDL_MW,MDL_MZ,MDL_MZ1,MDL_MB
     $ ,MDL_MW1,MDL_MH,MDL_MT1


      DOUBLE PRECISION MDL_WH1,MDL_WH,MDL_WW,MDL_WT,MDL_WZ,MDL_WW1
     $ ,MDL_WT1,MDL_WZ1

      COMMON/WIDTHS/ MDL_WH1,MDL_WH,MDL_WW,MDL_WT,MDL_WZ,MDL_WW1
     $ ,MDL_WT1,MDL_WZ1


      DOUBLE COMPLEX GC_386, GC_6, GC_7, GC_8, GC_64, GC_65, GC_67,
     $  GC_68, GC_69, GC_70, GC_72, GC_73, GC_80, GC_81, GC_82, GC_91,
     $  GC_92, GC_95, GC_96, GC_99, GC_112, GC_113, GC_116, GC_1, GC_2
     $ , GC_202, GC_203, GC_263, GC_264, GC_352, GC_566, GC_1025

      COMMON/COUPLINGS/ GC_386, GC_6, GC_7, GC_8, GC_64, GC_65, GC_67,
     $  GC_68, GC_69, GC_70, GC_72, GC_73, GC_80, GC_81, GC_82, GC_91,
     $  GC_92, GC_95, GC_96, GC_99, GC_112, GC_113, GC_116, GC_1, GC_2
     $ , GC_202, GC_203, GC_263, GC_264, GC_352, GC_566, GC_1025

