ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_topU3l_MwScheme_UFO'
     $ //'-massless_2t'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_386 = ', GC_386
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_65 = ', GC_65
      WRITE(*,2) 'GC_67 = ', GC_67
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_70 = ', GC_70
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_73 = ', GC_73
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_82 = ', GC_82
      WRITE(*,2) 'GC_91 = ', GC_91
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_95 = ', GC_95
      WRITE(*,2) 'GC_96 = ', GC_96
      WRITE(*,2) 'GC_99 = ', GC_99
      WRITE(*,2) 'GC_112 = ', GC_112
      WRITE(*,2) 'GC_113 = ', GC_113
      WRITE(*,2) 'GC_116 = ', GC_116
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_202 = ', GC_202
      WRITE(*,2) 'GC_203 = ', GC_203
      WRITE(*,2) 'GC_263 = ', GC_263
      WRITE(*,2) 'GC_264 = ', GC_264
      WRITE(*,2) 'GC_352 = ', GC_352
      WRITE(*,2) 'GC_566 = ', GC_566
      WRITE(*,2) 'GC_1025 = ', GC_1025
